kit:
  name: "MySQL Server on Docker"
  link: https://github.com/qubell-bazaar/component-mysql-docker
  applications:
    - name: "MySQL Server on Docker"
      manifest: https://raw.github.com/qubell-bazaar/component-mysql-docker/master/mysql.yml
  provider:
    name: Qubell
    link: http://qubell.com
  documentation:
    overview: |
      This application requires a Docker Service to be configured in your environment.
